create table acess (acess_id integer not null auto_increment, acess_level varchar(255), primary key (acess_id)) engine=InnoDB;
create table category (category_id integer not null auto_increment, category_description varchar(255), category_name varchar(255), url_image varchar(255), primary key (category_id)) engine=InnoDB;
create table collaborator (collaborator_id integer not null auto_increment, collaborator_name varchar(255) not null, collaborator_password varchar(255), collaborator_surname varchar(255) not null, email varchar(255) not null, acess_id_acess_id integer, primary key (collaborator_id)) engine=InnoDB;
create table feature (feature_id integer not null auto_increment, feature_name varchar(255), icon varchar(255), primary key (feature_id)) engine=InnoDB;
create table image (image_id integer not null auto_increment, title varchar(255), url_img varchar(255), product_id integer, primary key (image_id)) engine=InnoDB;
create table metaverse (metaverse_id integer not null auto_increment, metaverse_name varchar(255), primary key (metaverse_id)) engine=InnoDB;
create table product (product_id integer not null auto_increment, product_description varchar(255), product_name varchar(255), category_id integer, zone_id integer, primary key (product_id)) engine=InnoDB;
create table product_feature (product_id integer not null, feature_id integer not null, primary key (product_id, feature_id)) engine=InnoDB;
create table reservation (reservation_id integer not null auto_increment, checkin_date date, checkout_date date, primary key (reservation_id)) engine=InnoDB;
create table zone (zone_id integer not null auto_increment, latitude double precision not null, longitude double precision not null, metaverse_id integer, primary key (zone_id)) engine=InnoDB;
alter table collaborator add constraint UK_fxgjhrq4bfn052bv5v2fh8ag5 unique (email);
alter table collaborator add constraint FK89qfqln2jcg94qmap1m6ovw0p foreign key (acess_id_acess_id) references acess (acess_id);
alter table image add constraint FKgpextbyee3uk9u6o2381m7ft1 foreign key (product_id) references product (product_id);
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category (category_id);
alter table product add constraint FKwd7s3kq5jopyyalemod7ctlw foreign key (zone_id) references zone (zone_id);
alter table product add constraint FK9j8fp59no1ki30u30m8kvttsv foreign key (product_id) references zone (zone_id);
alter table product_feature add constraint FKgv1xq970xwg0q5k3jn9i23cc1 foreign key (feature_id) references feature (feature_id);
alter table product_feature add constraint FKp5iv62sge9f7yw66e5w2i2rhx foreign key (product_id) references product (product_id);
alter table zone add constraint FK99oi54i5eiob0hatsmyddh8rh foreign key (metaverse_id) references metaverse (metaverse_id);
create table acess (acess_id integer not null auto_increment, acess_level varchar(255), primary key (acess_id)) engine=InnoDB;
create table category (category_id integer not null auto_increment, category_description varchar(255), category_name varchar(255), url_image varchar(255), primary key (category_id)) engine=InnoDB;
create table collaborator (collaborator_id integer not null auto_increment, collaborator_name varchar(255) not null, collaborator_password varchar(255), collaborator_surname varchar(255) not null, email varchar(255) not null, acess_id_acess_id integer, primary key (collaborator_id)) engine=InnoDB;
create table feature (feature_id integer not null auto_increment, feature_name varchar(255), icon varchar(255), primary key (feature_id)) engine=InnoDB;
create table image (image_id integer not null auto_increment, title varchar(255), url_img varchar(255), product_id integer, primary key (image_id)) engine=InnoDB;
create table metaverse (metaverse_id integer not null auto_increment, metaverse_name varchar(255), primary key (metaverse_id)) engine=InnoDB;
create table product (product_id integer not null auto_increment, product_description varchar(255), product_name varchar(255), category_id integer, zone_id integer, primary key (product_id)) engine=InnoDB;
create table product_feature (product_id integer not null, feature_id integer not null, primary key (product_id, feature_id)) engine=InnoDB;
create table reservation (reservation_id integer not null auto_increment, checkin_date date, checkout_date date, primary key (reservation_id)) engine=InnoDB;
create table zone (zone_id integer not null auto_increment, latitude double precision not null, longitude double precision not null, metaverse_id integer, primary key (zone_id)) engine=InnoDB;
alter table collaborator add constraint UK_fxgjhrq4bfn052bv5v2fh8ag5 unique (email);
alter table collaborator add constraint FK89qfqln2jcg94qmap1m6ovw0p foreign key (acess_id_acess_id) references acess (acess_id);
alter table image add constraint FKgpextbyee3uk9u6o2381m7ft1 foreign key (product_id) references product (product_id);
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category (category_id);
alter table product add constraint FKwd7s3kq5jopyyalemod7ctlw foreign key (zone_id) references zone (zone_id);
alter table product add constraint FK9j8fp59no1ki30u30m8kvttsv foreign key (product_id) references zone (zone_id);
alter table product_feature add constraint FKgv1xq970xwg0q5k3jn9i23cc1 foreign key (feature_id) references feature (feature_id);
alter table product_feature add constraint FKp5iv62sge9f7yw66e5w2i2rhx foreign key (product_id) references product (product_id);
alter table zone add constraint FK99oi54i5eiob0hatsmyddh8rh foreign key (metaverse_id) references metaverse (metaverse_id);
create table acess (acess_id integer not null auto_increment, acess_level varchar(255), primary key (acess_id)) engine=InnoDB;
create table category (category_id integer not null auto_increment, category_description varchar(255), category_name varchar(255), url_image varchar(255), primary key (category_id)) engine=InnoDB;
create table collaborator (collaborator_id integer not null auto_increment, collaborator_name varchar(255) not null, collaborator_password varchar(255), collaborator_surname varchar(255) not null, email varchar(255) not null, acess_id_acess_id integer, primary key (collaborator_id)) engine=InnoDB;
create table feature (feature_id integer not null auto_increment, feature_name varchar(255), icon varchar(255), primary key (feature_id)) engine=InnoDB;
create table image (image_id integer not null auto_increment, title varchar(255), url_img varchar(255), product_id integer, primary key (image_id)) engine=InnoDB;
create table metaverse (metaverse_id integer not null auto_increment, metaverse_name varchar(255), primary key (metaverse_id)) engine=InnoDB;
create table product (product_id integer not null auto_increment, product_description varchar(255), product_name varchar(255), category_id integer, zone_id integer, primary key (product_id)) engine=InnoDB;
create table product_feature (product_id integer not null, feature_id integer not null, primary key (product_id, feature_id)) engine=InnoDB;
create table reservation (reservation_id integer not null auto_increment, checkin_date date, checkout_date date, primary key (reservation_id)) engine=InnoDB;
create table zone (zone_id integer not null auto_increment, latitude double precision not null, longitude double precision not null, metaverse_id integer, primary key (zone_id)) engine=InnoDB;
alter table collaborator add constraint UK_fxgjhrq4bfn052bv5v2fh8ag5 unique (email);
alter table collaborator add constraint FK89qfqln2jcg94qmap1m6ovw0p foreign key (acess_id_acess_id) references acess (acess_id);
alter table image add constraint FKgpextbyee3uk9u6o2381m7ft1 foreign key (product_id) references product (product_id);
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category (category_id);
alter table product add constraint FKwd7s3kq5jopyyalemod7ctlw foreign key (zone_id) references zone (zone_id);
alter table product add constraint FK9j8fp59no1ki30u30m8kvttsv foreign key (product_id) references zone (zone_id);
alter table product_feature add constraint FKgv1xq970xwg0q5k3jn9i23cc1 foreign key (feature_id) references feature (feature_id);
alter table product_feature add constraint FKp5iv62sge9f7yw66e5w2i2rhx foreign key (product_id) references product (product_id);
alter table zone add constraint FK99oi54i5eiob0hatsmyddh8rh foreign key (metaverse_id) references metaverse (metaverse_id);
create table acess (acess_id integer not null auto_increment, acess_level varchar(255), primary key (acess_id)) engine=InnoDB;
create table category (category_id integer not null auto_increment, category_description varchar(255), category_name varchar(255), url_image varchar(255), primary key (category_id)) engine=InnoDB;
create table collaborator (collaborator_id integer not null auto_increment, collaborator_name varchar(255) not null, collaborator_password varchar(255), collaborator_surname varchar(255) not null, email varchar(255) not null, acess_id_acess_id integer, primary key (collaborator_id)) engine=InnoDB;
create table feature (feature_id integer not null auto_increment, feature_name varchar(255), icon varchar(255), primary key (feature_id)) engine=InnoDB;
create table image (image_id integer not null auto_increment, title varchar(255), url_img varchar(255), product_id integer, primary key (image_id)) engine=InnoDB;
create table metaverse (metaverse_id integer not null auto_increment, metaverse_name varchar(255), primary key (metaverse_id)) engine=InnoDB;
create table product (product_id integer not null auto_increment, product_description varchar(255), product_name varchar(255), category_id integer, zone_id integer, primary key (product_id)) engine=InnoDB;
create table product_feature (product_id integer not null, feature_id integer not null, primary key (product_id, feature_id)) engine=InnoDB;
create table reservation (reservation_id integer not null auto_increment, checkin_date date, checkout_date date, primary key (reservation_id)) engine=InnoDB;
create table zone (zone_id integer not null auto_increment, latitude double precision not null, longitude double precision not null, metaverse_id integer, primary key (zone_id)) engine=InnoDB;
alter table collaborator add constraint UK_fxgjhrq4bfn052bv5v2fh8ag5 unique (email);
alter table collaborator add constraint FK89qfqln2jcg94qmap1m6ovw0p foreign key (acess_id_acess_id) references acess (acess_id);
alter table image add constraint FKgpextbyee3uk9u6o2381m7ft1 foreign key (product_id) references product (product_id);
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category (category_id);
alter table product add constraint FKwd7s3kq5jopyyalemod7ctlw foreign key (zone_id) references zone (zone_id);
alter table product add constraint FK9j8fp59no1ki30u30m8kvttsv foreign key (product_id) references zone (zone_id);
alter table product_feature add constraint FKgv1xq970xwg0q5k3jn9i23cc1 foreign key (feature_id) references feature (feature_id);
alter table product_feature add constraint FKp5iv62sge9f7yw66e5w2i2rhx foreign key (product_id) references product (product_id);
alter table zone add constraint FK99oi54i5eiob0hatsmyddh8rh foreign key (metaverse_id) references metaverse (metaverse_id);
create table acess (acess_id integer not null auto_increment, acess_level varchar(255), primary key (acess_id)) engine=InnoDB;
create table category (category_id integer not null auto_increment, category_description varchar(255), category_name varchar(255), url_image varchar(255), primary key (category_id)) engine=InnoDB;
create table collaborator (collaborator_id integer not null auto_increment, collaborator_name varchar(255) not null, collaborator_password varchar(255), collaborator_surname varchar(255) not null, email varchar(255) not null, acess_id_acess_id integer, primary key (collaborator_id)) engine=InnoDB;
create table feature (feature_id integer not null auto_increment, feature_name varchar(255), icon varchar(255), primary key (feature_id)) engine=InnoDB;
create table image (image_id integer not null auto_increment, title varchar(255), url_img varchar(255), product_id integer, primary key (image_id)) engine=InnoDB;
create table metaverse (metaverse_id integer not null auto_increment, metaverse_name varchar(255), primary key (metaverse_id)) engine=InnoDB;
create table product (product_id integer not null auto_increment, product_description varchar(255), product_name varchar(255), category_id integer, zone_id integer, primary key (product_id)) engine=InnoDB;
create table product_feature (product_id integer not null, feature_id integer not null, primary key (product_id, feature_id)) engine=InnoDB;
create table reservation (reservation_id integer not null auto_increment, checkin_date date, checkout_date date, primary key (reservation_id)) engine=InnoDB;
create table zone (zone_id integer not null auto_increment, latitude double precision not null, longitude double precision not null, metaverse_id integer, primary key (zone_id)) engine=InnoDB;
alter table collaborator add constraint UK_fxgjhrq4bfn052bv5v2fh8ag5 unique (email);
alter table collaborator add constraint FK89qfqln2jcg94qmap1m6ovw0p foreign key (acess_id_acess_id) references acess (acess_id);
alter table image add constraint FKgpextbyee3uk9u6o2381m7ft1 foreign key (product_id) references product (product_id);
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category (category_id);
alter table product add constraint FKwd7s3kq5jopyyalemod7ctlw foreign key (zone_id) references zone (zone_id);
alter table product add constraint FK9j8fp59no1ki30u30m8kvttsv foreign key (product_id) references zone (zone_id);
alter table product_feature add constraint FKgv1xq970xwg0q5k3jn9i23cc1 foreign key (feature_id) references feature (feature_id);
alter table product_feature add constraint FKp5iv62sge9f7yw66e5w2i2rhx foreign key (product_id) references product (product_id);
alter table zone add constraint FK99oi54i5eiob0hatsmyddh8rh foreign key (metaverse_id) references metaverse (metaverse_id);
create table acess (acess_id integer not null auto_increment, acess_level varchar(255), primary key (acess_id)) engine=InnoDB;
create table category (category_id integer not null auto_increment, category_description varchar(255), category_name varchar(255), url_image varchar(255), primary key (category_id)) engine=InnoDB;
create table collaborator (collaborator_id integer not null auto_increment, collaborator_name varchar(255) not null, collaborator_password varchar(255), collaborator_surname varchar(255) not null, email varchar(255) not null, acess_id_acess_id integer, primary key (collaborator_id)) engine=InnoDB;
create table feature (feature_id integer not null auto_increment, feature_name varchar(255), icon varchar(255), primary key (feature_id)) engine=InnoDB;
create table image (image_id integer not null auto_increment, title varchar(255), url_img varchar(255), product_id integer, primary key (image_id)) engine=InnoDB;
create table metaverse (metaverse_id integer not null auto_increment, metaverse_name varchar(255), primary key (metaverse_id)) engine=InnoDB;
create table product (product_id integer not null auto_increment, product_description varchar(255), product_name varchar(255), category_id integer, zone_id integer, primary key (product_id)) engine=InnoDB;
create table product_feature (product_id integer not null, feature_id integer not null, primary key (product_id, feature_id)) engine=InnoDB;
create table reservation (reservation_id integer not null auto_increment, checkin_date date, checkout_date date, primary key (reservation_id)) engine=InnoDB;
create table zone (zone_id integer not null auto_increment, latitude double precision not null, longitude double precision not null, metaverse_id integer, primary key (zone_id)) engine=InnoDB;
alter table collaborator add constraint UK_fxgjhrq4bfn052bv5v2fh8ag5 unique (email);
alter table collaborator add constraint FK89qfqln2jcg94qmap1m6ovw0p foreign key (acess_id_acess_id) references acess (acess_id);
alter table image add constraint FKgpextbyee3uk9u6o2381m7ft1 foreign key (product_id) references product (product_id);
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category (category_id);
alter table product add constraint FKwd7s3kq5jopyyalemod7ctlw foreign key (zone_id) references zone (zone_id);
alter table product add constraint FK9j8fp59no1ki30u30m8kvttsv foreign key (product_id) references zone (zone_id);
alter table product_feature add constraint FKgv1xq970xwg0q5k3jn9i23cc1 foreign key (feature_id) references feature (feature_id);
alter table product_feature add constraint FKp5iv62sge9f7yw66e5w2i2rhx foreign key (product_id) references product (product_id);
alter table zone add constraint FK99oi54i5eiob0hatsmyddh8rh foreign key (metaverse_id) references metaverse (metaverse_id);
create table acess (acess_id integer not null auto_increment, acess_level varchar(255), primary key (acess_id)) engine=InnoDB;
create table category (category_id integer not null auto_increment, category_description varchar(255), category_name varchar(255), url_image varchar(255), primary key (category_id)) engine=InnoDB;
create table collaborator (collaborator_id integer not null auto_increment, collaborator_name varchar(255) not null, collaborator_password varchar(255), collaborator_surname varchar(255) not null, email varchar(255) not null, acess_id_acess_id integer, primary key (collaborator_id)) engine=InnoDB;
create table feature (feature_id integer not null auto_increment, feature_name varchar(255), icon varchar(255), primary key (feature_id)) engine=InnoDB;
create table image (image_id integer not null auto_increment, title varchar(255), url_img varchar(255), product_id integer, primary key (image_id)) engine=InnoDB;
create table metaverse (metaverse_id integer not null auto_increment, metaverse_name varchar(255), primary key (metaverse_id)) engine=InnoDB;
create table product (product_id integer not null auto_increment, product_description varchar(255), product_name varchar(255), category_id integer, zone_id integer, primary key (product_id)) engine=InnoDB;
create table product_feature (product_id integer not null, feature_id integer not null, primary key (product_id, feature_id)) engine=InnoDB;
create table reservation (reservation_id integer not null auto_increment, checkin_date date, checkout_date date, primary key (reservation_id)) engine=InnoDB;
create table zone (zone_id integer not null auto_increment, latitude double precision not null, longitude double precision not null, metaverse_id integer, primary key (zone_id)) engine=InnoDB;
alter table collaborator add constraint UK_fxgjhrq4bfn052bv5v2fh8ag5 unique (email);
alter table collaborator add constraint FK89qfqln2jcg94qmap1m6ovw0p foreign key (acess_id_acess_id) references acess (acess_id);
alter table image add constraint FKgpextbyee3uk9u6o2381m7ft1 foreign key (product_id) references product (product_id);
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category (category_id);
alter table product add constraint FKwd7s3kq5jopyyalemod7ctlw foreign key (zone_id) references zone (zone_id);
alter table product add constraint FK9j8fp59no1ki30u30m8kvttsv foreign key (product_id) references zone (zone_id);
alter table product_feature add constraint FKgv1xq970xwg0q5k3jn9i23cc1 foreign key (feature_id) references feature (feature_id);
alter table product_feature add constraint FKp5iv62sge9f7yw66e5w2i2rhx foreign key (product_id) references product (product_id);
alter table zone add constraint FK99oi54i5eiob0hatsmyddh8rh foreign key (metaverse_id) references metaverse (metaverse_id);
create table acess (acess_id integer not null auto_increment, acess_level varchar(255), primary key (acess_id)) engine=InnoDB;
create table category (category_id integer not null auto_increment, category_description varchar(255), category_name varchar(255), url_image varchar(255), primary key (category_id)) engine=InnoDB;
create table collaborator (collaborator_id integer not null auto_increment, atualizado TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, collaborator_name varchar(255) not null, collaborator_password varchar(255), collaborator_surname varchar(255) not null, criado TIMESTAMP DEFAULT CURRENT_TIMESTAMP, email varchar(255) not null, acess_id_acess_id integer, primary key (collaborator_id)) engine=InnoDB;
create table feature (feature_id integer not null auto_increment, feature_name varchar(255), icon varchar(255), primary key (feature_id)) engine=InnoDB;
create table image (image_id integer not null auto_increment, title varchar(255), url_img varchar(255), product_id integer, primary key (image_id)) engine=InnoDB;
create table metaverse (metaverse_id integer not null auto_increment, metaverse_name varchar(255), primary key (metaverse_id)) engine=InnoDB;
create table product (product_id integer not null auto_increment, product_description varchar(255), product_name varchar(255), category_id integer, zone_id integer, primary key (product_id)) engine=InnoDB;
create table product_feature (product_id integer not null, feature_id integer not null, primary key (product_id, feature_id)) engine=InnoDB;
create table reservation (reservation_id integer not null auto_increment, atualizado TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, checkin_date datetime(6), checkin_hour datetime(6), checkout_date datetime(6), checkout_hour datetime(6), criado TIMESTAMP DEFAULT CURRENT_TIMESTAMP, product_id_product_id integer, primary key (reservation_id)) engine=InnoDB;
create table zone (zone_id integer not null auto_increment, latitude double precision not null, longitude double precision not null, metaverse_id integer, primary key (zone_id)) engine=InnoDB;
alter table collaborator add constraint UK_fxgjhrq4bfn052bv5v2fh8ag5 unique (email);
alter table collaborator add constraint FK89qfqln2jcg94qmap1m6ovw0p foreign key (acess_id_acess_id) references acess (acess_id);
alter table image add constraint FKgpextbyee3uk9u6o2381m7ft1 foreign key (product_id) references product (product_id);
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category (category_id);
alter table product add constraint FKwd7s3kq5jopyyalemod7ctlw foreign key (zone_id) references zone (zone_id);
alter table product add constraint FK9j8fp59no1ki30u30m8kvttsv foreign key (product_id) references zone (zone_id);
alter table product_feature add constraint FKgv1xq970xwg0q5k3jn9i23cc1 foreign key (feature_id) references feature (feature_id);
alter table product_feature add constraint FKp5iv62sge9f7yw66e5w2i2rhx foreign key (product_id) references product (product_id);
alter table reservation add constraint FKg1rful6olwt3pb2kicohnomjr foreign key (product_id_product_id) references product (product_id);
alter table zone add constraint FK99oi54i5eiob0hatsmyddh8rh foreign key (metaverse_id) references metaverse (metaverse_id);
create table acess (acess_id integer not null auto_increment, acess_level varchar(255), primary key (acess_id)) engine=InnoDB;
create table category (category_id integer not null auto_increment, category_description varchar(255), category_name varchar(255), url_image varchar(255), primary key (category_id)) engine=InnoDB;
create table collaborator (collaborator_id integer not null auto_increment, atualizado TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, collaborator_name varchar(255) not null, collaborator_password varchar(255), collaborator_surname varchar(255) not null, criado TIMESTAMP DEFAULT CURRENT_TIMESTAMP, email varchar(255) not null, acess_id_acess_id integer, primary key (collaborator_id)) engine=InnoDB;
create table feature (feature_id integer not null auto_increment, feature_name varchar(255), icon varchar(255), primary key (feature_id)) engine=InnoDB;
create table image (image_id integer not null auto_increment, title varchar(255), url_img varchar(255), product_id integer, primary key (image_id)) engine=InnoDB;
create table metaverse (metaverse_id integer not null auto_increment, metaverse_name varchar(255), primary key (metaverse_id)) engine=InnoDB;
create table product (product_id integer not null auto_increment, product_description varchar(255), product_name varchar(255), category_id integer, zone_id integer, primary key (product_id)) engine=InnoDB;
create table product_feature (product_id integer not null, feature_id integer not null, primary key (product_id, feature_id)) engine=InnoDB;
create table reservation (reservation_id integer not null auto_increment, atualizado TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, checkin_date datetime(6), checkin_hour datetime(6), checkout_date datetime(6), checkout_hour datetime(6), criado TIMESTAMP DEFAULT CURRENT_TIMESTAMP, product_id_product_id integer, primary key (reservation_id)) engine=InnoDB;
create table zone (zone_id integer not null auto_increment, latitude double precision not null, longitude double precision not null, metaverse_id integer, primary key (zone_id)) engine=InnoDB;
alter table collaborator add constraint UK_fxgjhrq4bfn052bv5v2fh8ag5 unique (email);
alter table collaborator add constraint FK89qfqln2jcg94qmap1m6ovw0p foreign key (acess_id_acess_id) references acess (acess_id);
alter table image add constraint FKgpextbyee3uk9u6o2381m7ft1 foreign key (product_id) references product (product_id);
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category (category_id);
alter table product add constraint FKwd7s3kq5jopyyalemod7ctlw foreign key (zone_id) references zone (zone_id);
alter table product add constraint FK9j8fp59no1ki30u30m8kvttsv foreign key (product_id) references zone (zone_id);
alter table product_feature add constraint FKgv1xq970xwg0q5k3jn9i23cc1 foreign key (feature_id) references feature (feature_id);
alter table product_feature add constraint FKp5iv62sge9f7yw66e5w2i2rhx foreign key (product_id) references product (product_id);
alter table reservation add constraint FKg1rful6olwt3pb2kicohnomjr foreign key (product_id_product_id) references product (product_id);
alter table zone add constraint FK99oi54i5eiob0hatsmyddh8rh foreign key (metaverse_id) references metaverse (metaverse_id);
create table acess (acess_id integer not null auto_increment, acess_level varchar(255), primary key (acess_id)) engine=InnoDB;
create table category (category_id integer not null auto_increment, category_description varchar(255), category_name varchar(255), url_image varchar(255), primary key (category_id)) engine=InnoDB;
create table collaborator (collaborator_id integer not null auto_increment, atualizado TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, collaborator_name varchar(255) not null, collaborator_password varchar(255), collaborator_surname varchar(255) not null, criado TIMESTAMP DEFAULT CURRENT_TIMESTAMP, email varchar(255) not null, acess_id_acess_id integer, primary key (collaborator_id)) engine=InnoDB;
create table feature (feature_id integer not null auto_increment, feature_name varchar(255), icon varchar(255), primary key (feature_id)) engine=InnoDB;
create table image (image_id integer not null auto_increment, title varchar(255), url_img varchar(255), product_id integer, primary key (image_id)) engine=InnoDB;
create table metaverse (metaverse_id integer not null auto_increment, metaverse_name varchar(255), primary key (metaverse_id)) engine=InnoDB;
create table product (product_id integer not null auto_increment, product_description varchar(255), product_name varchar(255), category_id integer, zone_id integer, primary key (product_id)) engine=InnoDB;
create table product_feature (product_id integer not null, feature_id integer not null, primary key (product_id, feature_id)) engine=InnoDB;
create table reservation (reservation_id integer not null auto_increment, atualizado TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, checkin_date datetime(6), checkin_hour datetime(6), checkout_date datetime(6), checkout_hour datetime(6), criado TIMESTAMP DEFAULT CURRENT_TIMESTAMP, product_id_product_id integer, primary key (reservation_id)) engine=InnoDB;
create table zone (zone_id integer not null auto_increment, latitude double precision not null, longitude double precision not null, metaverse_id integer, primary key (zone_id)) engine=InnoDB;
alter table collaborator add constraint UK_fxgjhrq4bfn052bv5v2fh8ag5 unique (email);
alter table collaborator add constraint FK89qfqln2jcg94qmap1m6ovw0p foreign key (acess_id_acess_id) references acess (acess_id);
alter table image add constraint FKgpextbyee3uk9u6o2381m7ft1 foreign key (product_id) references product (product_id);
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category (category_id);
alter table product add constraint FKwd7s3kq5jopyyalemod7ctlw foreign key (zone_id) references zone (zone_id);
alter table product add constraint FK9j8fp59no1ki30u30m8kvttsv foreign key (product_id) references zone (zone_id);
alter table product_feature add constraint FKgv1xq970xwg0q5k3jn9i23cc1 foreign key (feature_id) references feature (feature_id);
alter table product_feature add constraint FKp5iv62sge9f7yw66e5w2i2rhx foreign key (product_id) references product (product_id);
alter table reservation add constraint FKg1rful6olwt3pb2kicohnomjr foreign key (product_id_product_id) references product (product_id);
alter table zone add constraint FK99oi54i5eiob0hatsmyddh8rh foreign key (metaverse_id) references metaverse (metaverse_id);
create table acess (acess_id integer not null auto_increment, acess_level varchar(255), primary key (acess_id)) engine=InnoDB;
create table category (category_id integer not null auto_increment, category_description varchar(255), category_name varchar(255), url_image varchar(255), primary key (category_id)) engine=InnoDB;
create table collaborator (collaborator_id integer not null auto_increment, atualizado TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, collaborator_name varchar(255) not null, collaborator_password varchar(255), collaborator_surname varchar(255) not null, criado TIMESTAMP DEFAULT CURRENT_TIMESTAMP, email varchar(255) not null, acess_id_acess_id integer, primary key (collaborator_id)) engine=InnoDB;
create table feature (feature_id integer not null auto_increment, feature_name varchar(255), icon varchar(255), primary key (feature_id)) engine=InnoDB;
create table image (image_id integer not null auto_increment, title varchar(255), url_img varchar(255), product_id integer, primary key (image_id)) engine=InnoDB;
create table metaverse (metaverse_id integer not null auto_increment, metaverse_name varchar(255), primary key (metaverse_id)) engine=InnoDB;
create table product (product_id integer not null auto_increment, product_description varchar(255), product_name varchar(255), category_id integer, zone_id integer, primary key (product_id)) engine=InnoDB;
create table product_feature (product_id integer not null, feature_id integer not null, primary key (product_id, feature_id)) engine=InnoDB;
create table reservation (reservation_id integer not null auto_increment, atualizado TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, checkin_date datetime(6), checkin_hour datetime(6), checkout_date datetime(6), checkout_hour datetime(6), criado TIMESTAMP DEFAULT CURRENT_TIMESTAMP, product_id_product_id integer, primary key (reservation_id)) engine=InnoDB;
create table zone (zone_id integer not null auto_increment, latitude double precision not null, longitude double precision not null, metaverse_id integer, primary key (zone_id)) engine=InnoDB;
alter table collaborator add constraint UK_fxgjhrq4bfn052bv5v2fh8ag5 unique (email);
alter table collaborator add constraint FK89qfqln2jcg94qmap1m6ovw0p foreign key (acess_id_acess_id) references acess (acess_id);
alter table image add constraint FKgpextbyee3uk9u6o2381m7ft1 foreign key (product_id) references product (product_id);
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category (category_id);
alter table product add constraint FKwd7s3kq5jopyyalemod7ctlw foreign key (zone_id) references zone (zone_id);
alter table product add constraint FK9j8fp59no1ki30u30m8kvttsv foreign key (product_id) references zone (zone_id);
alter table product_feature add constraint FKgv1xq970xwg0q5k3jn9i23cc1 foreign key (feature_id) references feature (feature_id);
alter table product_feature add constraint FKp5iv62sge9f7yw66e5w2i2rhx foreign key (product_id) references product (product_id);
alter table reservation add constraint FKg1rful6olwt3pb2kicohnomjr foreign key (product_id_product_id) references product (product_id);
alter table zone add constraint FK99oi54i5eiob0hatsmyddh8rh foreign key (metaverse_id) references metaverse (metaverse_id);
create table acess (acess_id integer not null auto_increment, acess_level varchar(255), primary key (acess_id)) engine=InnoDB;
create table category (category_id integer not null auto_increment, category_description varchar(255), category_name varchar(255), url_image varchar(255), primary key (category_id)) engine=InnoDB;
create table collaborator (collaborator_id integer not null auto_increment, atualizado TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, collaborator_name varchar(255) not null, collaborator_password varchar(255), collaborator_surname varchar(255) not null, criado TIMESTAMP DEFAULT CURRENT_TIMESTAMP, email varchar(255) not null, acess_id_acess_id integer, primary key (collaborator_id)) engine=InnoDB;
create table feature (feature_id integer not null auto_increment, feature_name varchar(255), icon varchar(255), primary key (feature_id)) engine=InnoDB;
create table image (image_id integer not null auto_increment, title varchar(255), url_img varchar(255), product_id integer, primary key (image_id)) engine=InnoDB;
create table metaverse (metaverse_id integer not null auto_increment, metaverse_name varchar(255), primary key (metaverse_id)) engine=InnoDB;
create table product (product_id integer not null auto_increment, product_description varchar(255), product_name varchar(255), category_id integer, zone_id integer, primary key (product_id)) engine=InnoDB;
create table product_feature (product_id integer not null, feature_id integer not null, primary key (product_id, feature_id)) engine=InnoDB;
create table reservation (reservation_id integer not null auto_increment, atualizado TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, checkin_date datetime(6), checkin_hour datetime(6), checkout_date datetime(6), checkout_hour datetime(6), criado TIMESTAMP DEFAULT CURRENT_TIMESTAMP, collaborator_id_collaborator_id integer, product_id_product_id integer, primary key (reservation_id)) engine=InnoDB;
create table zone (zone_id integer not null auto_increment, latitude double precision not null, longitude double precision not null, metaverse_id integer, primary key (zone_id)) engine=InnoDB;
alter table collaborator add constraint UK_fxgjhrq4bfn052bv5v2fh8ag5 unique (email);
alter table collaborator add constraint FK89qfqln2jcg94qmap1m6ovw0p foreign key (acess_id_acess_id) references acess (acess_id);
alter table image add constraint FKgpextbyee3uk9u6o2381m7ft1 foreign key (product_id) references product (product_id);
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category (category_id);
alter table product add constraint FKwd7s3kq5jopyyalemod7ctlw foreign key (zone_id) references zone (zone_id);
alter table product add constraint FK9j8fp59no1ki30u30m8kvttsv foreign key (product_id) references zone (zone_id);
alter table product_feature add constraint FKgv1xq970xwg0q5k3jn9i23cc1 foreign key (feature_id) references feature (feature_id);
alter table product_feature add constraint FKp5iv62sge9f7yw66e5w2i2rhx foreign key (product_id) references product (product_id);
alter table reservation add constraint FKmnhn3kjalktiqy32y0nf97qne foreign key (collaborator_id_collaborator_id) references collaborator (collaborator_id);
alter table reservation add constraint FKg1rful6olwt3pb2kicohnomjr foreign key (product_id_product_id) references product (product_id);
alter table zone add constraint FK99oi54i5eiob0hatsmyddh8rh foreign key (metaverse_id) references metaverse (metaverse_id);
create table acess (acess_id integer not null auto_increment, acess_level varchar(255), primary key (acess_id)) engine=InnoDB;
create table category (category_id integer not null auto_increment, category_description varchar(255), category_name varchar(255), url_image varchar(255), primary key (category_id)) engine=InnoDB;
create table collaborator (collaborator_id integer not null auto_increment, atualizado TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, collaborator_name varchar(255) not null, collaborator_password varchar(255), collaborator_surname varchar(255) not null, criado TIMESTAMP DEFAULT CURRENT_TIMESTAMP, email varchar(255) not null, acess_id_acess_id integer, primary key (collaborator_id)) engine=InnoDB;
create table feature (feature_id integer not null auto_increment, feature_name varchar(255), icon varchar(255), primary key (feature_id)) engine=InnoDB;
create table image (image_id integer not null auto_increment, title varchar(255), url_img varchar(255), product_id integer, primary key (image_id)) engine=InnoDB;
create table metaverse (metaverse_id integer not null auto_increment, metaverse_name varchar(255), primary key (metaverse_id)) engine=InnoDB;
create table product (product_id integer not null auto_increment, product_description varchar(255), product_name varchar(255), category_id integer, zone_id integer, primary key (product_id)) engine=InnoDB;
create table product_feature (product_id integer not null, feature_id integer not null, primary key (product_id, feature_id)) engine=InnoDB;
create table reservation (reservation_id integer not null auto_increment, atualizado TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, checkin_date datetime(6), checkin_hour datetime(6), checkout_date datetime(6), checkout_hour datetime(6), criado TIMESTAMP DEFAULT CURRENT_TIMESTAMP, collaborator_id_collaborator_id integer, product_id_product_id integer, primary key (reservation_id)) engine=InnoDB;
create table zone (zone_id integer not null auto_increment, latitude double precision not null, longitude double precision not null, metaverse_id integer, primary key (zone_id)) engine=InnoDB;
alter table collaborator add constraint UK_fxgjhrq4bfn052bv5v2fh8ag5 unique (email);
alter table collaborator add constraint FK89qfqln2jcg94qmap1m6ovw0p foreign key (acess_id_acess_id) references acess (acess_id);
alter table image add constraint FKgpextbyee3uk9u6o2381m7ft1 foreign key (product_id) references product (product_id);
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category (category_id);
alter table product add constraint FKwd7s3kq5jopyyalemod7ctlw foreign key (zone_id) references zone (zone_id);
alter table product add constraint FK9j8fp59no1ki30u30m8kvttsv foreign key (product_id) references zone (zone_id);
alter table product_feature add constraint FKgv1xq970xwg0q5k3jn9i23cc1 foreign key (feature_id) references feature (feature_id);
alter table product_feature add constraint FKp5iv62sge9f7yw66e5w2i2rhx foreign key (product_id) references product (product_id);
alter table reservation add constraint FKmnhn3kjalktiqy32y0nf97qne foreign key (collaborator_id_collaborator_id) references collaborator (collaborator_id);
alter table reservation add constraint FKg1rful6olwt3pb2kicohnomjr foreign key (product_id_product_id) references product (product_id);
alter table zone add constraint FK99oi54i5eiob0hatsmyddh8rh foreign key (metaverse_id) references metaverse (metaverse_id);
create table acess (acess_id integer not null auto_increment, acess_level varchar(255), primary key (acess_id)) engine=InnoDB;
create table category (category_id integer not null auto_increment, category_description varchar(255), category_name varchar(255), url_image varchar(255), primary key (category_id)) engine=InnoDB;
create table collaborator (collaborator_id integer not null auto_increment, atualizado TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, collaborator_name varchar(255) not null, collaborator_password varchar(255), collaborator_surname varchar(255) not null, criado TIMESTAMP DEFAULT CURRENT_TIMESTAMP, email varchar(255) not null, acess_id_acess_id integer, primary key (collaborator_id)) engine=InnoDB;
create table feature (feature_id integer not null auto_increment, feature_name varchar(255), icon varchar(255), primary key (feature_id)) engine=InnoDB;
create table image (image_id integer not null auto_increment, title varchar(255), url_img varchar(255), product_id integer, primary key (image_id)) engine=InnoDB;
create table metaverse (metaverse_id integer not null auto_increment, metaverse_name varchar(255), primary key (metaverse_id)) engine=InnoDB;
create table product (product_id integer not null auto_increment, product_description varchar(255), product_name varchar(255), category_id integer, zone_id integer, primary key (product_id)) engine=InnoDB;
create table product_feature (product_id integer not null, feature_id integer not null, primary key (product_id, feature_id)) engine=InnoDB;
create table reservation (reservation_id integer not null auto_increment, atualizado TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, checkin_date datetime(6), checkin_hour datetime(6), checkout_date datetime(6), checkout_hour datetime(6), criado TIMESTAMP DEFAULT CURRENT_TIMESTAMP, collaborator_id_collaborator_id integer, product_id_product_id integer, primary key (reservation_id)) engine=InnoDB;
create table zone (zone_id integer not null auto_increment, latitude double precision not null, longitude double precision not null, metaverse_id integer, primary key (zone_id)) engine=InnoDB;
alter table collaborator add constraint UK_fxgjhrq4bfn052bv5v2fh8ag5 unique (email);
alter table collaborator add constraint FK89qfqln2jcg94qmap1m6ovw0p foreign key (acess_id_acess_id) references acess (acess_id);
alter table image add constraint FKgpextbyee3uk9u6o2381m7ft1 foreign key (product_id) references product (product_id);
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category (category_id);
alter table product add constraint FKwd7s3kq5jopyyalemod7ctlw foreign key (zone_id) references zone (zone_id);
alter table product add constraint FK9j8fp59no1ki30u30m8kvttsv foreign key (product_id) references zone (zone_id);
alter table product_feature add constraint FKgv1xq970xwg0q5k3jn9i23cc1 foreign key (feature_id) references feature (feature_id);
alter table product_feature add constraint FKp5iv62sge9f7yw66e5w2i2rhx foreign key (product_id) references product (product_id);
alter table reservation add constraint FKmnhn3kjalktiqy32y0nf97qne foreign key (collaborator_id_collaborator_id) references collaborator (collaborator_id);
alter table reservation add constraint FKg1rful6olwt3pb2kicohnomjr foreign key (product_id_product_id) references product (product_id);
alter table zone add constraint FK99oi54i5eiob0hatsmyddh8rh foreign key (metaverse_id) references metaverse (metaverse_id);
